# Generated by Django 4.1.4 on 2022-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sroll_no', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('slastname', models.CharField(max_length=30)),
            ],
        ),
    ]
